### ISSUE TITLE
🖐️ Unable to build the project looks like some dependencies are missing.

### ISSUE THREAD

**Issue by Kasahs** [dagger/hello-dagger#7]
### What happened? What did you expect to happen?

When I clone and try to build the project I get:
```shell
➜  hello-dagger git:(main) ls
Dockerfile        dagger.json       main.go           public
LICENSE           go.mod            package-lock.json src
README.md         go.sum            package.json      tsconfig.json
➜  hello-dagger git:(main) go get
➜  hello-dagger git:(main) go build
# main
./main.go:12:44: undefined: Optional
./main.go:12:63: undefined: Container
./main.go:19:39: undefined: Optional
./main.go:19:58: undefined: Service
./main.go:24:37: undefined: Optional
./main.go:24:56: undefined: Container
./main.go:31:37: undefined: Optional
./main.go:31:56: undefined: Directory
./main.go:36:57: undefined: Optional
./main.go:43:69: undefined: Optional
./main.go:43:69: too many errors
```
In the main.go file I can see that several names are undefined
on importing dagger several of these are solved but some remain:

```golang
import (
	"context"
	. "dagger.io/dagger" // added this import
)
```
result:
```shell
➜  hello-dagger git:(main) ✗ go build
# main
./main.go:15:9: undefined: dag
./main.go:46:9: undefined: dag
./main.go:49:60: undefined: Node
./main.go:50:9: undefined: dag
./main.go:53:14: undefined: dag

```

Not sure how to fix the remaining ones. I thought this might be solved as I go along the tutorial but that doesn't seem to be the case. Need some guidance here.

**Comment by gerhard** [comment]
cc @vikram-dagger

**Comment by vikram-dagger** [comment]
@Kasahs can you clarify which tutorial you tried to follow?

**Comment by migmartri** [comment]
Same problem here. This is the tutorial I am following https://docs.dagger.io/zenith/user/quickstart/623939/call

Note that the calls using dagger don't fail but instead is our editor or local building of the go code is the one that complains.

**Comment by migmartri** [comment]
I think part of the issue here is that `dagger.gen.go` is not in this example. `dagger mod init` seems to generate this file

**Comment by vikram-dagger** [comment]
To clarify this, you aren't intended to be able to `go build` modules, they won't run correctly even if they build. You have to use `dagger call` to invoke them.

**Comment by migmartri** [comment]
Hi @vikram-dagger, thanks for the response.

To me, the biggest confusion comes because the code that comes out of the example doesn't compile, not that it can't be built. It shows missing dependencies in the code.

![image](https://github.com/dagger/hello-dagger/assets/24523/7dafe06e-ce9d-4e92-bc55-354ecf387082)

The main culprit seems to be that there is no `dagger.gen.go` file (and in fact it's .gitignored), which seems to be the one including all the core and module dependencies.

`dagger mod init` seems to add it during creation, so the code in main.go compiles as expected.

```sh
$ dagger mod init --name=chainloop --sdk=go
$ tree .
.
├── dagger.gen.go
├── dagger.json
├── go.mod
```

Coming back to this `hello-dagger` example. I can "fix it" by running `dagger mod sync` so this issue boils down to two points

- Is the dagger.gen.go meant to be checked in the repo? That would make it closer to how people handle generated files in go i.e protobuffer's
- If it's not supposed to be there. Should the quickstart include a step to generate this dependency file? Or did I miss a step? 

Thanks!

**Comment by sipsma** [comment]
@migmartri all good questions and something we're iterating on actively :-)

The upcoming release of dagger (Feb 1st) changes the Go SDK to no longer `.gitignore` `dagger.gen.go`. Technically it's not *required* that it gets checked into a repo because the dagger engine will generate it on the fly if it's not present whenever you use `dagger call`. However, in order to cooperate with existing CI linters, it often is required to check it in, so we removed it from `.gitignore`.

So generally yes, it's best to check `dagger.gen.go` into the repo, similar to protobufs like you mentioned.

**Comment by vikram-dagger** [comment]
This application is in the process of being updated for a new quickstart, so closing this issue.
